<?php
/**
 * Administration functions for term objects
 * Supports callbacks generated by social-filters.php
 *
 * @package WP_SEO_Social
 */

// Add Term context.
/**
 * Call printing function for the OG title input for a new term.
 */
function wp_seo_social_term_id_to_the_add_term_meta_og_title_input() {
	wp_seo_social_the_meta_og_title_input( null );
}

/**
 * Call printing function for the OG title character count for a new term.
 */
function wp_seo_social_term_id_to_the_add_term_og_title_character_count() {
	wp_seo_social_the_og_title_character_count( 0 );
}

/**
 * Call printing function for the OG description input for a new term.
 */
function wp_seo_social_term_id_to_the_add_term_meta_og_description_input() {
	wp_seo_social_the_meta_og_description_input( null );
}

/**
 * Call printing function for the OG description character count for a new term.
 */
function wp_seo_social_term_id_to_the_add_term_og_description_character_count() {
	wp_seo_social_the_og_description_character_count( 0 );
}

/**
 * Call printing function for the OG image input for a new term
 */
function wp_seo_social_term_id_to_the_add_term_meta_og_image_input() {
	wp_seo_social_the_meta_og_image_input( null );
}

/**
 * Call printing function for the OG description input for a new term.
 */
function wp_seo_social_term_id_to_the_add_term_meta_og_type_input() {
	wp_seo_social_the_meta_og_type_input( null );
}

// Edit Term context.
/**
 * Call printing function for the OG title input for an existing term.
 *
 * @param WP_Term $term Term object.
 */
function wp_seo_social_term_id_to_the_edit_term_meta_og_title_input( $term ) {
	wp_seo_social_the_meta_og_title_input( get_term_meta( $term->term_id, 'og_title', true ) );
}

/**
 * Call printing function for the OG title character count for an existing term.
 *
 * @param WP_Term $term Term object.
 */
function wp_seo_social_term_id_to_the_edit_term_og_title_character_count( $term ) {
	wp_seo_social_the_og_title_character_count( wp_seo_get_the_display_character_count( get_term_meta( $term->term_id, 'og_title', true ) ) );
}

/** Call printing function for the OG title character count for an existing term.
 *
 * @param WP_Term $term Term object.
 */
function wp_seo_social_term_id_to_the_edit_term_og_description_character_count( $term ) {
	wp_seo_social_the_og_description_character_count( wp_seo_get_the_display_character_count( get_term_meta( $term->term_id, 'og_description', true ) ) );
}

/**
 * Call printing function for the OG title input for an existing term.
 *
 * @param WP_Term $term Term object.
 */
function wp_seo_social_term_id_to_the_edit_term_meta_og_description_input( $term ) {
	wp_seo_social_the_meta_og_description_input( get_term_meta( $term->term_id, 'og_description', true ) );
}

/**
 * Call printing function for the OG title input for an existing term.
 *
 * @param WP_Term $term Term object.
 */
function wp_seo_social_term_id_to_the_edit_term_meta_og_image_input( $term ) {
	wp_seo_social_the_meta_og_image_input( get_term_meta( $term->term_id, 'og_image', true ) );
}

/**
 * Call printing function for the OG title input for an existing term.
 *
 * @param WP_Term $term Term object.
 */
function wp_seo_social_term_id_to_the_edit_term_meta_og_type_input( $term ) {
	wp_seo_social_the_meta_og_type_input( get_term_meta( $term->term_id, 'og_type', true ) );
}
